/**
 * Do our pads agree with a footprint somebody else published?
 *
 * ## A third opinion, from outside this repo entirely
 *
 * Every other check here is internal. `bench:copper` compares the copper to our
 * record, `bench:dimensions` compares our record to our own hand reading, and
 * `bench:joints` compares two pages of the vendor's document to each other. All
 * three share one weakness: if a package is read wrongly and consistently, they
 * agree with each other about the wrong answer.
 *
 * KiCad's official footprint library does not. It is generated by KiCad's own
 * IPC-7351 tooling from JEDEC and vendor data, by other people, with no
 * knowledge of this project. For a package that has an entry there, its pads are
 * an independent statement of where the copper goes.
 *
 * ## What agreement and disagreement each mean
 *
 * They are NOT expected to be identical, and a bench demanding that would report
 * every correct part as wrong. This product builds from the vendor's own printed
 * pattern wherever the datasheet prints one, and a vendor's house pattern
 * legitimately differs from IPC's by a few tenths - the same spread
 * `bench:copper` documents at length for its own computed patterns.
 *
 * What a third source is good for is the OTHER kind of error: the whole package
 * being wrong. A sibling drawing read off the wrong page, a decimal point, an
 * axis swap and a unit mix-up each move the copper by millimetres, and no amount
 * of house style accounts for that. So the report is a spread rather than a
 * verdict, and the eye goes to the tail.
 *
 * ## Cost and the air gap
 *
 * Free apart from bandwidth, and the network use is this BENCH fetching public
 * reference data on a developer machine. Nothing about a customer's document
 * leaves anywhere: the product never calls this file, and the fetched library is
 * cached under `.kicad-ref/` so a rerun is offline.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildFootprintGeometry, FootprintUnavailableError } from "../exporters";
import { defect } from "./inject";
import { replayRecords } from "./replay";
import { thermalPadNumber } from "../geometry";
import type { Pad } from "../geometry";
import type { ResolvedPart } from "../types";

const CACHE = join(process.cwd(), ".kicad-ref");
const PROJECT = "kicad%2Flibraries%2Fkicad-footprints";

/**
 * The libraries a corpus of integrated circuits can land in.
 *
 * Named rather than fetched wholesale because the full library is over 14,000
 * files across 130 directories, almost all of them connectors, passives and
 * mechanical parts this product does not generate.
 */
const LIBRARIES = [
  "Package_SO",
  "Package_QFP",
  "Package_DFN_QFN",
  "Package_SON",
  "Package_SO_J-Lead",
  "Package_LGA",
  "Package_BGA",
  "Package_CSP",
  "Package_DIP",
  "Package_TO_SOT_SMD",
  "Package_TO_SOT_THT"
];

async function cached(name: string, url: string): Promise<string | null> {
  if (!existsSync(CACHE)) mkdirSync(CACHE, { recursive: true });
  const path = join(CACHE, name);
  if (existsSync(path)) return readFileSync(path, "utf8");
  try {
    const response = await fetch(url, { signal: AbortSignal.timeout(45_000) });
    if (!response.ok) return null;
    const body = await response.text();
    writeFileSync(path, body);
    return body;
  } catch {
    return null;
  }
}

async function index(): Promise<string[]> {
  const names: string[] = [];
  for (const library of LIBRARIES) {
    for (let page = 1; ; page += 1) {
      const body = await cached(
        `index-${library}-${page}.json`,
        `https://gitlab.com/api/v4/projects/${PROJECT}/repository/tree?path=${library}.pretty&per_page=100&page=${page}`
      );
      if (!body) break;
      let entries: Array<{ name: string; path: string }>;
      try {
        entries = JSON.parse(body) as Array<{ name: string; path: string }>;
      } catch {
        break;
      }
      if (!Array.isArray(entries) || entries.length === 0) break;
      names.push(...entries.filter((entry) => entry.name.endsWith(".kicad_mod")).map((entry) => entry.path));
      if (entries.length < 100) break;
    }
  }
  return names;
}

/**
 * What KiCad's own filename states about the package.
 *
 * Their convention is systematic and machine-written, which is what makes this
 * work without a hand-typed table mapping our package names onto theirs:
 * `SOIC-8_3.9x4.9mm_P1.27mm`, `TSSOP-16_4.4x5mm_P0.65mm`, `LQFP-64_10x10mm_P0.5mm`.
 * A hand-typed table would be a per-family constant, which is exactly what this
 * codebase spent 2026-08-14 deleting.
 */
/**
 * WHAT LEAD FORM A KICAD LIBRARY IS ABOUT.
 *
 * Needed because pin count, pitch and body do NOT identify a package on their
 * own, and assuming they did produced this bench's second false finding. A 5x5
 * VQFN-32 at 0.5 mm and a 5x5 LQFP-32 at 0.5 mm agree on all three and share
 * nothing else: the QFN's terminals are under the body on a 4.8 mm span and the
 * QFP's leads reach out past it on 6.4. DAC81404 is a VQFN and was duly reported
 * as 1.55 mm out against a quad flat PACK.
 *
 * The library directory states the form outright, which is why this needs no
 * table of package names. Same distinction `ipc7351.ts` refuses to compute
 * across: a no-lead terminal and a gull-wing lead are different objects.
 */
function formOf(path: string): "nolead" | "gullwing" | "grid" | "through-hole" | null {
  const library = path.split("/")[0];
  if (/^Package_(DFN_QFN|SON|LGA)/.test(library)) return "nolead";
  if (/^Package_(QFP|SO|TO_SOT_SMD)/.test(library)) return "gullwing";
  if (/^Package_(BGA|CSP)/.test(library)) return "grid";
  if (/^Package_(DIP|TO_SOT_THT)/.test(library)) return "through-hole";
  return null;
}

function describes(path: string): { pins: number; body: [number, number]; pitchMm: number } | null {
  const file = path.split("/").pop()!.replace(/\.kicad_mod$/, "");
  // A thermal-via variant is the same copper with stitching added, and a
  // hand-solder variant is deliberately NOT the IPC pattern. Neither is a second
  // opinion about this package.
  if (/_ThermalVias|_HandSolder|Housing|_Pad[0-9]/.test(file)) return null;
  const pins = file.match(/-(\d+)(?:-\d+EP)?[-_]/);
  const body = file.match(/_(\d+(?:\.\d+)?)x(\d+(?:\.\d+)?)mm/);
  const pitch = file.match(/_P(\d+(?:\.\d+)?)mm/);
  if (!pins || !body || !pitch) return null;
  return { pins: Number(pins[1]), body: [Number(body[1]), Number(body[2])], pitchMm: Number(pitch[1]) };
}

interface Land {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** Pad centres and sizes out of a `.kicad_mod`, in mm. */
function padsOf(text: string): Land[] {
  const out: Land[] = [];
  const pattern =
    /\(pad\s+"[^"]*"\s+(\w+)\s+\w+[\s\S]*?\(at ([-\d.]+) ([-\d.]+)(?:\s+[-\d.]+)?\)[\s\S]*?\(size ([\d.]+) ([\d.]+)\)/g;
  for (const match of text.matchAll(pattern)) {
    if (match[1] === "np_thru_hole") continue;
    out.push({ x: Number(match[2]), y: Number(match[3]), w: Number(match[4]), h: Number(match[5]) });
  }
  return out;
}

/** The centre-to-centre span across the widest opposing pair of rows, and one land's size. */
function measure(pads: Land[]): { spanMm: number; padLengthMm: number; padWidthMm: number } | null {
  if (pads.length < 2) return null;
  // The exposed pad is much the biggest by area and is not a lead land.
  const areas = pads.map((pad) => pad.w * pad.h).sort((a, b) => b - a);
  const lands =
    areas.length > 4 && areas[0] > areas[Math.floor(areas.length / 2)] * 3
      ? pads.filter((pad) => pad.w * pad.h < areas[0] - 1e-9)
      : pads;
  if (lands.length < 2) return null;
  // WHICH AXIS THE LEADS RUN ALONG, from the pads' SHAPE rather than their
  // spread.
  //
  // Spread is degenerate and it produced this bench's only finding on its first
  // run. A 20-pin TSSOP has ten lands a side at 0.65 mm, so its row is 5.85 mm
  // long and its centre span is 5.85 to 5.90: the two axes are the same size to
  // within a rounding error, and the test picked x for our file and y for the
  // published one. LM5117 was duly reported as having a land rotated ninety
  // degrees, with the length and width almost exactly exchanged, which is what a
  // real rotated land looks like. It was the instrument.
  //
  // Shape is not degenerate. A land is LONG in the direction its lead runs, on
  // every footprint either generator produces, so the majority verdict over all
  // the lands names the axis outright.
  const longerAlongX = lands.filter((pad) => pad.w > pad.h).length;
  const axis: "x" | "y" = longerAlongX * 2 >= lands.length ? "x" : "y";
  const rows = new Map<number, number>();
  for (const pad of lands) {
    const key = Math.round(pad[axis] * 1000) / 1000;
    rows.set(key, (rows.get(key) ?? 0) + 1);
  }
  const widest = Math.max(...rows.values());
  let lines = [...rows].filter(([, count]) => count === widest).map(([line]) => line);
  // AN ASYMMETRIC PACKAGE STILL HAS TWO ROWS. A SOT-23-5 puts three lands on one
  // side and two on the other, so the widest-row rule finds exactly ONE row and
  // gives up: five parts came back as "our own pads could not be measured" when
  // their footprints are perfectly ordinary. Falling back to every row with more
  // than one land keeps the quads working, since a quad's rows all tie.
  if (lines.length < 2) lines = [...rows].filter(([, count]) => count >= 2).map(([line]) => line);
  if (lines.length < 2) return null;
  // FOUND BY PROXIMITY, because the row keys above are rounded to a thousandth
  // and a pad's own coordinate is not. Matching on equality found nothing and
  // crashed on the first part.
  const example = lands.find((pad) => Math.abs(pad[axis] - lines[0]) < 0.0011)!;
  if (!example) return null;
  return {
    spanMm: Math.max(...lines) - Math.min(...lines),
    padLengthMm: axis === "x" ? example.w : example.h,
    padWidthMm: axis === "x" ? example.h : example.w
  };
}

/** The same three numbers, out of our own emitted pads. */
function measureOurs(part: ResolvedPart, pads: Pad[]) {
  const padNumber = thermalPadNumber(part.pinCount);
  const lands = pads.filter(
    (pad) => pad.mounting === "smd" && pad.number !== "EP" && !(part.exposedPad && pad.number === padNumber)
  );
  return measure(lands.map((pad) => ({ x: pad.centre.xMm, y: pad.centre.yMm, w: pad.widthMm, h: pad.heightMm })));
}

const near = (a: number, b: number, slack: number) => Math.abs(a - b) <= slack;

async function main(): Promise<void> {
  const paths = await index();
  console.log(`\nIndexed ${paths.length} published KiCad footprints across ${LIBRARIES.length} libraries.`);
  if (paths.length === 0) {
    console.log("No index could be fetched and none is cached. Run once with network access.\n");
    return;
  }

  const described = paths
    .map((path) => ({ path, spec: describes(path) }))
    .filter((entry): entry is { path: string; spec: NonNullable<ReturnType<typeof describes>> } => entry.spec !== null);

  interface Row {
    part: string;
    match: string;
    ours: NonNullable<ReturnType<typeof measure>>;
    theirs: NonNullable<ReturnType<typeof measure>>;
  }
  const rows: Row[] = [];
  const unmatched: string[] = [];

  for (const part of replayRecords()) {
    let pads: Pad[];
    try {
      // A LAND PATTERN A THIRD TOO BIG IN EVERY DIRECTION, which is the size of
      // disagreement this bench exists to see against somebody else's published
      // footprint. Applied to the copper only.
      pads = defect("published.pads", buildFootprintGeometry(part, "B").pads, (all) =>
        all.map((pad) => ({
          ...pad,
          centre: { xMm: pad.centre.xMm * 1.35, yMm: pad.centre.yMm * 1.35 },
          widthMm: pad.widthMm * 1.35,
          heightMm: pad.heightMm * 1.35
        }))
      );
    } catch (error) {
      if (!(error instanceof FootprintUnavailableError)) unmatched.push(`${part.partNumber}: failed to build`);
      continue;
    }
    const pitch = part.dimensions.pitchMm;
    const bodyA = part.dimensions.bodyLengthMm;
    const bodyB = part.dimensions.bodyWidthMm;
    if (pitch === null || bodyA === null || bodyB === null) {
      unmatched.push(`${part.partNumber}: no pitch or body to match on`);
      continue;
    }

    // MATCHED ON THE PHYSICAL PACKAGE, never on the package NAME. Two vendors
    // spell one package four ways and one spelling covers two packages, so a
    // name match is a coin toss. Pin count, pitch and both body dimensions
    // identify a package outright, in either axis order.
    const candidates = described.filter(
      (entry) =>
        // THE LEAD FORM FIRST. See `formOf`.
        //
        // A record with no form read is compared against nothing rather than
        // against whatever matches its body: an unknown form is not a licence to
        // pick, and a wrong pairing here does not report a weak result, it
        // reports a defect that is not there.
        formOf(entry.path) === part.dimensions.leadForm &&
        entry.spec.pins === part.pinCount &&
        near(entry.spec.pitchMm, pitch, 0.005) &&
        ((near(entry.spec.body[0], bodyB, 0.1) && near(entry.spec.body[1], bodyA, 0.1)) ||
          (near(entry.spec.body[0], bodyA, 0.1) && near(entry.spec.body[1], bodyB, 0.1)))
    );
    if (candidates.length === 0) {
      unmatched.push(`${part.partNumber}: no published footprint for this package`);
      continue;
    }

    const ours = measureOurs(part, pads);
    if (!ours) {
      unmatched.push(`${part.partNumber}: our own pads could not be measured`);
      continue;
    }
    const text = await cached(
      candidates[0].path.replace(/\//g, "_"),
      `https://gitlab.com/kicad/libraries/kicad-footprints/-/raw/master/${candidates[0].path}`
    );
    if (!text) {
      unmatched.push(`${part.partNumber}: the published file could not be fetched`);
      continue;
    }
    const theirs = measure(padsOf(text));
    if (!theirs) {
      unmatched.push(`${part.partNumber}: the published file's pads could not be measured`);
      continue;
    }
    rows.push({ part: part.partNumber, match: candidates[0].path.split("/").pop()!.replace(/\.kicad_mod$/, ""), ours, theirs });
  }

  console.log(`Matched ${rows.length} of our footprints to a published one on pin count, pitch and body.\n`);
  console.log(
    `  ${"part".padEnd(18)} ${"published footprint".padEnd(32)} ${"span".padStart(16)} ${"pad length".padStart(16)} ${"pad width".padStart(16)}`
  );
  const deltas: Array<{ part: string; span: number; length: number; width: number; match: string }> = [];
  for (const row of rows.sort((left, right) => left.part.localeCompare(right.part))) {
    const span = row.ours.spanMm - row.theirs.spanMm;
    const length = row.ours.padLengthMm - row.theirs.padLengthMm;
    const width = row.ours.padWidthMm - row.theirs.padWidthMm;
    deltas.push({ part: row.part, span, length, width, match: row.match });
    const show = (mine: number, theirs: number, delta: number) =>
      `${mine.toFixed(2)}/${theirs.toFixed(2)} ${(delta >= 0 ? "+" : "") + delta.toFixed(2)}`.padStart(16);
    console.log(
      `  ${row.part.padEnd(18)} ${row.match.slice(0, 32).padEnd(32)} ${show(row.ours.spanMm, row.theirs.spanMm, span)} ` +
        `${show(row.ours.padLengthMm, row.theirs.padLengthMm, length)} ${show(row.ours.padWidthMm, row.theirs.padWidthMm, width)}`
    );
  }

  console.log("\n  Ours minus theirs, in mm. Both are legitimate patterns, so the eye goes to the tail.\n");
  for (const key of ["span", "length", "width"] as const) {
    const values = deltas.map((delta) => delta[key]).sort((left, right) => left - right);
    if (values.length === 0) continue;
    const worst = [...deltas].sort((left, right) => Math.abs(right[key]) - Math.abs(left[key]))[0];
    console.log(
      `    ${key.padEnd(7)} median ${values[Math.floor(values.length / 2)].toFixed(3).padStart(7)}   ` +
        `range ${values[0].toFixed(3)} to ${values[values.length - 1].toFixed(3)}   worst ${worst.part} at ${worst[key].toFixed(3)}`
    );
  }

  // THE TAIL, and the bound that names it.
  //
  // A millimetre on the span or the land length, and half of one across the
  // land. Not a tolerance: a vendor's house pattern and IPC's differ by tenths,
  // and every defect shape this project has shipped moves the copper by whole
  // millimetres. Anything in between is worth a person's eye either way.
  const gross = deltas.filter(
    (delta) => Math.abs(delta.span) > 1 || Math.abs(delta.length) > 1 || Math.abs(delta.width) > 0.5
  );
  console.log(`\n  ${gross.length} footprint(s) differ by more than a vendor's house style explains:`);
  for (const delta of gross) {
    console.log(
      `    ${delta.part.padEnd(18)} span ${delta.span.toFixed(2).padStart(7)}  length ${delta.length.toFixed(2).padStart(7)}  ` +
        `width ${delta.width.toFixed(2).padStart(7)}  vs ${delta.match}`
    );
  }
  if (gross.length === 0) console.log("    none");

  console.log(`\n  ${unmatched.length} not compared:`);
  const grouped = new Map<string, number>();
  const namesByWhy = new Map<string, string[]>();
  for (const line of unmatched) {
    const why = line.split(": ").slice(1).join(": ") || line;
    grouped.set(why, (grouped.get(why) ?? 0) + 1);
    namesByWhy.set(why, [...(namesByWhy.get(why) ?? []), line.split(": ")[0]]);
  }
  for (const [why, count] of [...grouped].sort((left, right) => right[1] - left[1])) {
    // NAMED, not counted. A tally of things nobody looked at is a number nobody
    // can act on, and "our own pads could not be measured" is a sentence about
    // THIS product that deserves a part number beside it.
    console.log(`    ${String(count).padStart(3)}  ${why.padEnd(44)} ${(namesByWhy.get(why) ?? []).join(" ")}`);
  }
  console.log("");
}

if (process.argv[1]?.endsWith("published.ts")) {
  void main();
}
